# Generated by Django 5.2.12 on 2026-04-15 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0003_membership_applied_at_alter_membership_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collective',
            name='members',
            field=models.ManyToManyField(related_name='collectives', through='osolot_server.Membership', through_fields=('collective', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
