# Generated by Django 5.2.12 on 2026-04-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0005_alter_user_options_alter_collective_admission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
