# Generated by Django 5.2.12 on 2026-04-20 22:24

import osolot_server.models.collective
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0006_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='slug',
            field=models.CharField(default=osolot_server.models.collective.generate_collective_slug, max_length=16),
        ),
    ]
