# Generated by Django 5.2.12 on 2026-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0008_alter_collective_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], default='public'),
        ),
    ]
