# Generated by Django 5.2.12 on 2026-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0014_friendship_user_friends_friendship_unique_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_with_new_friends_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_friendships',
            field=models.ManyToManyField(related_name='shared_posts', to='osolot_server.friendship'),
        ),
    ]
