# Generated by Django 5.2.12 on 2026-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0015_post_share_with_new_friends_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_sent', 'Pending Sent'), ('pending_received', 'Pending Received')], default='pending_sent', max_length=31),
        ),
    ]
