/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Osolot API
 * API for managing decentralized libraries of things.
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './axios-instance';
/**
 * Admin and moderators only.
 */
export type UpdateMembershipRequestStatus = Status | null;

/**
 * Admin only.
 */
export type UpdateMembershipRequestRole = Role | null;

/**
 * Requesting user only.
 */
export type UpdateMembershipRequestApplicationMessage = string | null;

export interface UpdateMembershipRequest {
  /** Requesting user only. */
  application_message?: UpdateMembershipRequestApplicationMessage;
  /** Admin only. */
  role?: UpdateMembershipRequestRole;
  /** Admin and moderators only. */
  status?: UpdateMembershipRequestStatus;
}

export interface JoinCollectiveRequest {
  /** @maxLength 10000 */
  application_message?: string;
}

export type MembershipDetailUpdatedAt = string | null;

export type MembershipDetailJoinedAt = string | null;

export type MembershipDetailApprovedBy = UserSummary | null;

export type MembershipDetailAppliedAt = string | null;

export type MembershipDetailApplicationMessage = string | null;

export interface MembershipDetail {
  application_message?: MembershipDetailApplicationMessage;
  applied_at?: MembershipDetailAppliedAt;
  approved_by?: MembershipDetailApprovedBy;
  joined_at?: MembershipDetailJoinedAt;
  summary: MembershipSummary;
  updated_at?: MembershipDetailUpdatedAt;
}

/**
 * Message to users who apply for membership.
 */
export type CollectiveSettingsApplicationQuestion = string | null;

export interface CollectiveSettings {
  admission_type?: string;
  /** Message to users who apply for membership. */
  application_question?: CollectiveSettingsApplicationQuestion;
  /** @maxLength 10000 */
  description: string;
  /** @maxLength 255 */
  name: string;
  visibility?: string;
}

export type UserSummaryLastName = string | null;

export type UserSummaryId = number | null;

export type UserSummaryFirstName = string | null;

export interface UserSummary {
  first_name?: UserSummaryFirstName;
  id?: UserSummaryId;
  last_name?: UserSummaryLastName;
  /**
   * Required. 150 characters or fewer. Letters, digits, and _.- only.
   * @maxLength 150
   */
  username: string;
}

export type Status = typeof Status[keyof typeof Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  active: 'active',
  pending: 'pending',
} as const;

export type Role = typeof Role[keyof typeof Role];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Role = {
  admin: 'admin',
  moderator: 'moderator',
  member: 'member',
} as const;

export interface CollectiveSummary {
  admission_type?: string;
  /** @maxLength 10000 */
  description: string;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 16 */
  slug?: string;
  visibility?: string;
}

export interface MembershipSummary {
  collective: CollectiveSummary;
  role: Role;
  status: Status;
  user: UserSummary;
}

export interface CollectiveDetail {
  application_question: string;
  members: MembershipSummary[];
  summary: CollectiveSummary;
}

export type UpdateProfileRequestLastName = string | null;

export type UpdateProfileRequestFirstName = string | null;

export type UpdateProfileRequestBio = string | null;

export interface UpdateProfileRequest {
  bio?: UpdateProfileRequestBio;
  first_name?: UpdateProfileRequestFirstName;
  last_name?: UpdateProfileRequestLastName;
  /**
   * Required. 150 characters or fewer. Letters, digits, and _.- only.
   * @maxLength 150
   */
  username: string;
}

export type UserProfileLastName = string | null;

export type UserProfileId = number | null;

export type UserProfileFirstName = string | null;

export type UserProfileBio = string | null;

export interface UserProfile {
  bio?: UserProfileBio;
  /** @maxLength 254 */
  email: string;
  email_verified?: boolean;
  first_name?: UserProfileFirstName;
  id?: UserProfileId;
  last_name?: UserProfileLastName;
  /**
   * Required. 150 characters or fewer. Letters, digits, and _.- only.
   * @maxLength 150
   */
  username: string;
}

export interface VerifyEmailConfirmIn {
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface VerifyEmailRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface PasswordResetConfirmIn {
  /** @minLength 8 */
  new_password: string;
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface PasswordResetRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface MessageOut {
  message: string;
}

export interface RefreshIn {
  refresh: string;
}

export interface AccessTokenOut {
  access: string;
}

export interface LoginIn {
  /**
   * @minLength 3
   * @maxLength 254
   */
  identifier: string;
  password: string;
}

export interface RegisterIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 3
   * @maxLength 31
   */
  username: string;
}

export interface TokenPairOut {
  access: string;
  refresh: string;
}





  export const getOsolotAPI = () => {
/**
 * @summary Register
 */
const osolotServerApiAuthRegister = (
    registerIn: RegisterIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerIn
    },
      );
    }
  
/**
 * @summary Login
 */
const osolotServerApiAuthLogin = (
    loginIn: LoginIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginIn
    },
      );
    }
  
/**
 * @summary Refresh
 */
const osolotServerApiAuthRefresh = (
    refreshIn: RefreshIn,
 ) => {
      return customInstance<AccessTokenOut>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshIn
    },
      );
    }
  
/**
 * @summary Password Reset Request
 */
const osolotServerApiAuthPasswordResetRequest = (
    passwordResetRequestIn: PasswordResetRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetRequestIn
    },
      );
    }
  
/**
 * @summary Password Reset Confirm
 */
const osolotServerApiAuthPasswordResetConfirm = (
    passwordResetConfirmIn: PasswordResetConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirmIn
    },
      );
    }
  
/**
 * @summary Email Verification Request
 */
const osolotServerApiAuthEmailVerificationRequest = (
    verifyEmailRequestIn: VerifyEmailRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailRequestIn
    },
      );
    }
  
/**
 * @summary Email Verification Confirm
 */
const osolotServerApiAuthEmailVerificationConfirm = (
    verifyEmailConfirmIn: VerifyEmailConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailConfirmIn
    },
      );
    }
  
/**
 * @summary Me
 */
const osolotServerApiUsersMe = (
    
 ) => {
      return customInstance<UserProfile>(
      {url: `/api/users/my/profile`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Me
 */
const osolotServerApiUsersUpdateMe = (
    updateProfileRequest: UpdateProfileRequest,
 ) => {
      return customInstance<UserProfile>(
      {url: `/api/users/my/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileRequest
    },
      );
    }
  
/**
 * List all memberships for the current user, including pending memberships.
 * @summary List My Memberships
 */
const osolotServerApiUsersListMyMemberships = (
    
 ) => {
      return customInstance<MembershipSummary[]>(
      {url: `/api/users/my/memberships`, method: 'GET'
    },
      );
    }
  
/**
 * List all collectives visible to the current user.
 * @summary List Collectives
 */
const osolotServerApiCollectivesListCollectives = (
    
 ) => {
      return customInstance<CollectiveSummary[]>(
      {url: `/api/collectives/`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Collective
 */
const osolotServerApiCollectivesCreateCollective = (
    collectiveSettings: CollectiveSettings,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: collectiveSettings
    },
      );
    }
  
/**
 * @summary Get Collective
 */
const osolotServerApiCollectivesGetCollective = (
    collectiveSlug: string,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/${collectiveSlug}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Collective
 */
const osolotServerApiCollectivesUpdateCollective = (
    collectiveSlug: string,
    collectiveSettings: CollectiveSettings,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/${collectiveSlug}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: collectiveSettings
    },
      );
    }
  
/**
 * @summary Delete Collective
 */
const osolotServerApiCollectivesDeleteCollective = (
    collectiveSlug: string,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/collectives/${collectiveSlug}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Memberships
 */
const osolotServerApiCollectiveMembershipsListMemberships = (
    collectiveSlug: string,
 ) => {
      return customInstance<MembershipSummary[]>(
      {url: `/api/collectives/${collectiveSlug}/members`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Join Collective
 */
const osolotServerApiCollectiveMembershipsJoinCollective = (
    collectiveSlug: string,
    joinCollectiveRequest: JoinCollectiveRequest,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveSlug}/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinCollectiveRequest
    },
      );
    }
  
/**
 * @summary Get Membership
 */
const osolotServerApiCollectiveMembershipsGetMembership = (
    collectiveSlug: string,
    userId: number,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveSlug}/membership/${userId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Membership
 */
const osolotServerApiCollectiveMembershipsUpdateMembership = (
    collectiveSlug: string,
    userId: number,
    updateMembershipRequest: UpdateMembershipRequest,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveSlug}/membership/${userId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMembershipRequest
    },
      );
    }
  
/**
 * @summary Delete Membership
 */
const osolotServerApiCollectiveMembershipsDeleteMembership = (
    collectiveSlug: string,
    userId: number,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/collectives/${collectiveSlug}/membership/${userId}`, method: 'DELETE'
    },
      );
    }
  
return {osolotServerApiAuthRegister,osolotServerApiAuthLogin,osolotServerApiAuthRefresh,osolotServerApiAuthPasswordResetRequest,osolotServerApiAuthPasswordResetConfirm,osolotServerApiAuthEmailVerificationRequest,osolotServerApiAuthEmailVerificationConfirm,osolotServerApiUsersMe,osolotServerApiUsersUpdateMe,osolotServerApiUsersListMyMemberships,osolotServerApiCollectivesListCollectives,osolotServerApiCollectivesCreateCollective,osolotServerApiCollectivesGetCollective,osolotServerApiCollectivesUpdateCollective,osolotServerApiCollectivesDeleteCollective,osolotServerApiCollectiveMembershipsListMemberships,osolotServerApiCollectiveMembershipsJoinCollective,osolotServerApiCollectiveMembershipsGetMembership,osolotServerApiCollectiveMembershipsUpdateMembership,osolotServerApiCollectiveMembershipsDeleteMembership}};
export type OsolotServerApiAuthRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRegister']>>>
export type OsolotServerApiAuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthLogin']>>>
export type OsolotServerApiAuthRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRefresh']>>>
export type OsolotServerApiAuthPasswordResetRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthPasswordResetRequest']>>>
export type OsolotServerApiAuthPasswordResetConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthPasswordResetConfirm']>>>
export type OsolotServerApiAuthEmailVerificationRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthEmailVerificationRequest']>>>
export type OsolotServerApiAuthEmailVerificationConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthEmailVerificationConfirm']>>>
export type OsolotServerApiUsersMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUsersMe']>>>
export type OsolotServerApiUsersUpdateMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUsersUpdateMe']>>>
export type OsolotServerApiUsersListMyMembershipsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUsersListMyMemberships']>>>
export type OsolotServerApiCollectivesListCollectivesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesListCollectives']>>>
export type OsolotServerApiCollectivesCreateCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesCreateCollective']>>>
export type OsolotServerApiCollectivesGetCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesGetCollective']>>>
export type OsolotServerApiCollectivesUpdateCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesUpdateCollective']>>>
export type OsolotServerApiCollectivesDeleteCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesDeleteCollective']>>>
export type OsolotServerApiCollectiveMembershipsListMembershipsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsListMemberships']>>>
export type OsolotServerApiCollectiveMembershipsJoinCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsJoinCollective']>>>
export type OsolotServerApiCollectiveMembershipsGetMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsGetMembership']>>>
export type OsolotServerApiCollectiveMembershipsUpdateMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsUpdateMembership']>>>
export type OsolotServerApiCollectiveMembershipsDeleteMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsDeleteMembership']>>>
