/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Osolot API
 * API for managing decentralized libraries of things.
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './axios-instance';
export type UpdateMembershipRequestStatus = string | null;

export type UpdateMembershipRequestRole = string | null;

export type UpdateMembershipRequestApplicationMessage = string | null;

export interface UpdateMembershipRequest {
  application_message?: UpdateMembershipRequestApplicationMessage;
  role?: UpdateMembershipRequestRole;
  status?: UpdateMembershipRequestStatus;
}

export interface JoinCollectiveRequest {
  /** @maxLength 100000 */
  application_message?: string;
}

export type MembershipDetailJoinedAt = string | null;

export interface CollectiveSettings {
  /** @maxLength 31 */
  admission_type?: string;
  /** @maxLength 100000 */
  application_question?: string;
  /** @maxLength 100000 */
  description?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @maxLength 31 */
  visibility?: string;
}

export interface UserSummary {
  first_name: string;
  id: number;
  last_name: string;
}

export type MembershipDetailApprovedBy = UserSummary | null;

export interface CollectiveSummary {
  admission_type: string;
  description: string;
  id: number;
  name: string;
  visibility: string;
}

export interface MembershipSummary {
  collective: CollectiveSummary;
  role: string;
  status: string;
  user: UserSummary;
}

export interface MembershipDetail {
  application_message: string;
  applied_at: string;
  approved_by?: MembershipDetailApprovedBy;
  joined_at?: MembershipDetailJoinedAt;
  summary: MembershipSummary;
  updated_at: string;
}

export interface CollectiveDetail {
  application_question: string;
  members: MembershipSummary[];
  summary: CollectiveSummary;
}

export type UpdateProfileRequestLastName = string | null;

export type UpdateProfileRequestFirstName = string | null;

export interface UpdateProfileRequest {
  first_name?: UpdateProfileRequestFirstName;
  last_name?: UpdateProfileRequestLastName;
}

export interface UserProfile {
  email: string;
  email_verified: boolean;
  first_name: string;
  id: number;
  last_name: string;
}

export interface VerifyEmailConfirmIn {
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface VerifyEmailRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface PasswordResetConfirmIn {
  /** @minLength 8 */
  new_password: string;
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface PasswordResetRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface MessageOut {
  message: string;
}

export interface RefreshIn {
  refresh: string;
}

export interface AccessTokenOut {
  access: string;
}

export interface LoginIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  password: string;
}

export interface RegisterIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @minLength 8 */
  password: string;
}

export interface TokenPairOut {
  access: string;
  refresh: string;
}





  export const getOsolotAPI = () => {
/**
 * @summary Register
 */
const osolotServerApiAuthRegister = (
    registerIn: RegisterIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerIn
    },
      );
    }
  
/**
 * @summary Login
 */
const osolotServerApiAuthLogin = (
    loginIn: LoginIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginIn
    },
      );
    }
  
/**
 * @summary Refresh
 */
const osolotServerApiAuthRefresh = (
    refreshIn: RefreshIn,
 ) => {
      return customInstance<AccessTokenOut>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshIn
    },
      );
    }
  
/**
 * @summary Password Reset Request
 */
const osolotServerApiAuthPasswordResetRequest = (
    passwordResetRequestIn: PasswordResetRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetRequestIn
    },
      );
    }
  
/**
 * @summary Password Reset Confirm
 */
const osolotServerApiAuthPasswordResetConfirm = (
    passwordResetConfirmIn: PasswordResetConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirmIn
    },
      );
    }
  
/**
 * @summary Email Verification Request
 */
const osolotServerApiAuthEmailVerificationRequest = (
    verifyEmailRequestIn: VerifyEmailRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailRequestIn
    },
      );
    }
  
/**
 * @summary Email Verification Confirm
 */
const osolotServerApiAuthEmailVerificationConfirm = (
    verifyEmailConfirmIn: VerifyEmailConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailConfirmIn
    },
      );
    }
  
/**
 * @summary Me
 */
const osolotServerApiUsersMe = (
    
 ) => {
      return customInstance<UserProfile>(
      {url: `/api/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Me
 */
const osolotServerApiUsersUpdateMe = (
    updateProfileRequest: UpdateProfileRequest,
 ) => {
      return customInstance<UserProfile>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileRequest
    },
      );
    }
  
/**
 * @summary List Public Collectives
 */
const osolotServerApiCollectivesListPublicCollectives = (
    
 ) => {
      return customInstance<CollectiveSummary[]>(
      {url: `/api/collectives/`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Collective
 */
const osolotServerApiCollectivesCreateCollective = (
    collectiveSettings: CollectiveSettings,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: collectiveSettings
    },
      );
    }
  
/**
 * @summary List My Collectives
 */
const osolotServerApiCollectivesListMyCollectives = (
    
 ) => {
      return customInstance<CollectiveSummary[]>(
      {url: `/api/collectives/mine`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Get Collective
 */
const osolotServerApiCollectivesGetCollective = (
    collectiveId: number,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/${collectiveId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Collective
 */
const osolotServerApiCollectivesUpdateCollective = (
    collectiveId: number,
    collectiveSettings: CollectiveSettings,
 ) => {
      return customInstance<CollectiveDetail>(
      {url: `/api/collectives/${collectiveId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: collectiveSettings
    },
      );
    }
  
/**
 * @summary Delete Collective
 */
const osolotServerApiCollectivesDeleteCollective = (
    collectiveId: number,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/collectives/${collectiveId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Memberships
 */
const osolotServerApiCollectiveMembershipsListMemberships = (
    collectiveId: number,
 ) => {
      return customInstance<MembershipSummary[]>(
      {url: `/api/collectives/${collectiveId}/members`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Join Collective
 */
const osolotServerApiCollectiveMembershipsJoinCollective = (
    collectiveId: number,
    joinCollectiveRequest: JoinCollectiveRequest,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveId}/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinCollectiveRequest
    },
      );
    }
  
/**
 * @summary Get Membership
 */
const osolotServerApiCollectiveMembershipsGetMembership = (
    collectiveId: number,
    userId: number,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveId}/membership/${userId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Membership
 */
const osolotServerApiCollectiveMembershipsUpdateMembership = (
    collectiveId: number,
    userId: number,
    updateMembershipRequest: UpdateMembershipRequest,
 ) => {
      return customInstance<MembershipDetail>(
      {url: `/api/collectives/${collectiveId}/membership/${userId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMembershipRequest
    },
      );
    }
  
/**
 * @summary Delete Membership
 */
const osolotServerApiCollectiveMembershipsDeleteMembership = (
    collectiveId: number,
    userId: number,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/collectives/${collectiveId}/membership/${userId}`, method: 'DELETE'
    },
      );
    }
  
return {osolotServerApiAuthRegister,osolotServerApiAuthLogin,osolotServerApiAuthRefresh,osolotServerApiAuthPasswordResetRequest,osolotServerApiAuthPasswordResetConfirm,osolotServerApiAuthEmailVerificationRequest,osolotServerApiAuthEmailVerificationConfirm,osolotServerApiUsersMe,osolotServerApiUsersUpdateMe,osolotServerApiCollectivesListPublicCollectives,osolotServerApiCollectivesCreateCollective,osolotServerApiCollectivesListMyCollectives,osolotServerApiCollectivesGetCollective,osolotServerApiCollectivesUpdateCollective,osolotServerApiCollectivesDeleteCollective,osolotServerApiCollectiveMembershipsListMemberships,osolotServerApiCollectiveMembershipsJoinCollective,osolotServerApiCollectiveMembershipsGetMembership,osolotServerApiCollectiveMembershipsUpdateMembership,osolotServerApiCollectiveMembershipsDeleteMembership}};
export type OsolotServerApiAuthRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRegister']>>>
export type OsolotServerApiAuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthLogin']>>>
export type OsolotServerApiAuthRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRefresh']>>>
export type OsolotServerApiAuthPasswordResetRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthPasswordResetRequest']>>>
export type OsolotServerApiAuthPasswordResetConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthPasswordResetConfirm']>>>
export type OsolotServerApiAuthEmailVerificationRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthEmailVerificationRequest']>>>
export type OsolotServerApiAuthEmailVerificationConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthEmailVerificationConfirm']>>>
export type OsolotServerApiUsersMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUsersMe']>>>
export type OsolotServerApiUsersUpdateMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUsersUpdateMe']>>>
export type OsolotServerApiCollectivesListPublicCollectivesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesListPublicCollectives']>>>
export type OsolotServerApiCollectivesCreateCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesCreateCollective']>>>
export type OsolotServerApiCollectivesListMyCollectivesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesListMyCollectives']>>>
export type OsolotServerApiCollectivesGetCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesGetCollective']>>>
export type OsolotServerApiCollectivesUpdateCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesUpdateCollective']>>>
export type OsolotServerApiCollectivesDeleteCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectivesDeleteCollective']>>>
export type OsolotServerApiCollectiveMembershipsListMembershipsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsListMemberships']>>>
export type OsolotServerApiCollectiveMembershipsJoinCollectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsJoinCollective']>>>
export type OsolotServerApiCollectiveMembershipsGetMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsGetMembership']>>>
export type OsolotServerApiCollectiveMembershipsUpdateMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsUpdateMembership']>>>
export type OsolotServerApiCollectiveMembershipsDeleteMembershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiCollectiveMembershipsDeleteMembership']>>>
