/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Osolot API
 * API for managing decentralized libraries of things.
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './axios-instance';
export type UserUpdateInLastName = string | null;

export type UserUpdateInFirstName = string | null;

export interface UserUpdateIn {
  first_name?: UserUpdateInFirstName;
  last_name?: UserUpdateInLastName;
}

export interface UserOut {
  email: string;
  email_verified: boolean;
  first_name: string;
  id: number;
  last_name: string;
}

export interface VerifyEmailConfirmIn {
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface VerifyEmailRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface PasswordResetConfirmIn {
  /** @minLength 8 */
  new_password: string;
  /** @minLength 1 */
  token: string;
  /** @minLength 1 */
  uid: string;
}

export interface PasswordResetRequestIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
}

export interface MessageOut {
  message: string;
}

export interface RefreshIn {
  refresh: string;
}

export interface AccessTokenOut {
  access: string;
}

export interface LoginIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  password: string;
}

export interface RegisterIn {
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  /** @minLength 8 */
  password: string;
}

export interface TokenPairOut {
  access: string;
  refresh: string;
}





  export const getOsolotAPI = () => {
/**
 * @summary Register
 */
const osolotServerApiAuthRoutesRegister = (
    registerIn: RegisterIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerIn
    },
      );
    }
  
/**
 * @summary Login
 */
const osolotServerApiAuthRoutesLogin = (
    loginIn: LoginIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginIn
    },
      );
    }
  
/**
 * @summary Refresh
 */
const osolotServerApiAuthRoutesRefresh = (
    refreshIn: RefreshIn,
 ) => {
      return customInstance<AccessTokenOut>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshIn
    },
      );
    }
  
/**
 * @summary Password Reset Request
 */
const osolotServerApiAuthRoutesPasswordResetRequest = (
    passwordResetRequestIn: PasswordResetRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetRequestIn
    },
      );
    }
  
/**
 * @summary Password Reset Confirm
 */
const osolotServerApiAuthRoutesPasswordResetConfirm = (
    passwordResetConfirmIn: PasswordResetConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/password-reset/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirmIn
    },
      );
    }
  
/**
 * @summary Email Verification Request
 */
const osolotServerApiAuthRoutesEmailVerificationRequest = (
    verifyEmailRequestIn: VerifyEmailRequestIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailRequestIn
    },
      );
    }
  
/**
 * @summary Email Verification Confirm
 */
const osolotServerApiAuthRoutesEmailVerificationConfirm = (
    verifyEmailConfirmIn: VerifyEmailConfirmIn,
 ) => {
      return customInstance<MessageOut>(
      {url: `/api/auth/verify-email/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailConfirmIn
    },
      );
    }
  
/**
 * @summary Me
 */
const osolotServerApiUserRoutesMe = (
    
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Me
 */
const osolotServerApiUserRoutesUpdateMe = (
    userUpdateIn: UserUpdateIn,
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateIn
    },
      );
    }
  
return {osolotServerApiAuthRoutesRegister,osolotServerApiAuthRoutesLogin,osolotServerApiAuthRoutesRefresh,osolotServerApiAuthRoutesPasswordResetRequest,osolotServerApiAuthRoutesPasswordResetConfirm,osolotServerApiAuthRoutesEmailVerificationRequest,osolotServerApiAuthRoutesEmailVerificationConfirm,osolotServerApiUserRoutesMe,osolotServerApiUserRoutesUpdateMe}};
export type OsolotServerApiAuthRoutesRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesRegister']>>>
export type OsolotServerApiAuthRoutesLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesLogin']>>>
export type OsolotServerApiAuthRoutesRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesRefresh']>>>
export type OsolotServerApiAuthRoutesPasswordResetRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesPasswordResetRequest']>>>
export type OsolotServerApiAuthRoutesPasswordResetConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesPasswordResetConfirm']>>>
export type OsolotServerApiAuthRoutesEmailVerificationRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesEmailVerificationRequest']>>>
export type OsolotServerApiAuthRoutesEmailVerificationConfirmResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiAuthRoutesEmailVerificationConfirm']>>>
export type OsolotServerApiUserRoutesMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUserRoutesMe']>>>
export type OsolotServerApiUserRoutesUpdateMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerApiUserRoutesUpdateMe']>>>
